local string, table, ipairs, pairs = string, table, ipairs, pairs
local lgi = require("lgi")

local constants = require("lgir.annotate.constants")
local enums = require("lgir.annotate.enums")
local funcs = require("lgir.annotate.functions")
local structs = require("lgir.annotate.structs")
local utils = require("lgir.utils")

---@param file file*
---@param typelib table
---@return nil
local function write_header(file, typelib)
  local template = [[
---@meta
---@diagnostic disable: duplicate-doc-field
-- Autogenerated with lgir
-- Name: %s
-- Version: %s]]

  file:write(string.format(template, typelib._name, typelib._version))

  if typelib._dependencies ~= nil then
    local deps = {}
    for name, version in pairs(typelib._dependencies) do
      table.insert(deps, ("%s-%s"):format(name, version))
    end

    file:write("\n-- Dependencies: ", table.concat(deps, ", "))
  end
end

---Writes annotations to a file.
---@param gir_docs lgir.gir_docs
---@param filename string
---@return nil
return function(gir_docs, filename)
  local typelib = lgi.require(gir_docs.name, gir_docs.version):_resolve(true)

  local file, err = io.open(filename, "w")
  if file == nil then
    return err
  end

  write_header(file, typelib)

  local enum_classes, enum_fields = enums.list(typelib._enum, gir_docs.enums)
  local bit_classes, bit_fields = enums.list(typelib._bitfield, gir_docs.bitfields)
  local union_classes, union_fields = structs.list(typelib._union, gir_docs.unions)
  local struct_classes, struct_fields = structs.list(typelib._struct, gir_docs.structs)
  local iface_classes, iface_fields = structs.list(typelib._interface, gir_docs.interfaces, true)
  local classes, class_fields = structs.list(typelib._class, gir_docs.classes, true)

  local function write_sections(...)
    for _, lines in ipairs({ ... }) do
      if lines ~= nil then
        file:write("\n", table.concat(lines, "\n"))
      end
    end
  end

  -- Before repository definition
  -- Basic types, structs, interfaces, and classes
  write_sections(enum_classes, bit_classes)
  if gir_docs.callbacks ~= nil then
    file:write("\n", table.concat(funcs.callback_list(typelib._name, gir_docs.callbacks), "\n"))
  end
  write_sections(union_classes, struct_classes, iface_classes, classes)

  -- Annotate repository and fields
  file:write("\n\n", "---@class ", typelib._name)

  if typelib._constant ~= nil then
    file:write("\n", table.concat(constants.list(typelib._constant, gir_docs.constants), "\n"))
  end
  write_sections(enum_fields, bit_fields, union_fields, struct_fields, iface_fields, class_fields)

  file:write("\n", "local ", typelib._name, " = {}")

  -- Annotate repository functions
  if typelib._function ~= nil and gir_docs.functions ~= nil then
    local fns = funcs.function_list(typelib._name, gir_docs.functions, utils.keys(typelib._function))
    file:write("\n", table.concat(fns, "\n"))
  end

  file:close()
end
