local string, table = string, table
local lgi = require("lgi")

local write_enums = require("lgir.annotate.enums")
local write_funcs = require("lgir.annotate.functions")

local module_template = [[
---@class %s
local %s = {}]]

---@param file file*
---@param typelib table
local function write_header(file, typelib)
  local template = [[
---@meta
---@diagnostic disable: duplicate-doc-field
-- Autogenerated with lgir
-- Name: %s
-- Version: %s]]

  file:write(string.format(template, typelib._name, typelib._version))

  if typelib._dependencies ~= nil then
    local deps = {}
    for name, version in pairs(typelib._dependencies) do
      table.insert(deps, string.format("%s-%s", name, version))
    end

    file:write(string.format("\n-- Dependencies: %s", table.concat(deps, ", ")))
  end
end

return function(gir_docs, filename)
  local typelib = lgi.require(gir_docs.name, gir_docs.version):_resolve(true)

  local file, err = io.open(filename, "w")
  if file == nil then
    return err
  end

  write_header(file, typelib)

  if typelib._enum ~= nil and gir_docs.enums ~= nil then
    file:write("\n\n", table.concat(write_enums(typelib._enum, gir_docs.enums), "\n"))
  end
  if typelib._bitfield ~= nil and gir_docs.bitfields ~= nil then
    file:write("\n\n", table.concat(write_enums(typelib._bitfield, gir_docs.bitfields), "\n"))
  end

  file:write("\n\n", string.format(module_template, typelib._name, typelib._name))

  if typelib._function ~= nil and gir_docs.functions ~= nil then
    local funcs = table.concat(write_funcs(typelib._name, typelib._function, gir_docs.functions), "\n")
    file:write("\n\n", funcs)
  end

  file:close()
end
