local string, table = string, table
local lgi = require("lgi")

local constants = require("lgir.annotate.constants")
local enums = require("lgir.annotate.enums")
local funcs = require("lgir.annotate.functions")
local structs = require("lgir.annotate.structs")
local utils = require("lgir.utils")

---@param file file*
---@param typelib table
---@return nil
local function write_header(file, typelib)
  local template = [[
---@meta
---@diagnostic disable: duplicate-doc-field
-- Autogenerated with lgir
-- Name: %s
-- Version: %s]]

  file:write(string.format(template, typelib._name, typelib._version))

  if typelib._dependencies ~= nil then
    local deps = {}
    for name, version in pairs(typelib._dependencies) do
      table.insert(deps, ("%s-%s"):format(name, version))
    end

    file:write("\n-- Dependencies: ", table.concat(deps, ", "))
  end
end

---@param gir_docs lgir.gir_docs
---@param filename string
---@return nil
return function(gir_docs, filename)
  local typelib = lgi.require(gir_docs.name, gir_docs.version):_resolve(true)

  local file, err = io.open(filename, "w")
  if file == nil then
    return err
  end

  write_header(file, typelib)

  local enum_classes, enum_fields = enums.list(typelib._enum, gir_docs.enums)
  local bit_classes, bit_fields = enums.list(typelib._bitfield, gir_docs.bitfields)
  local struct_classes, struct_fields = structs.list(typelib._struct, gir_docs.structs)

  if enum_classes ~= nil then
    file:write("\n", table.concat(enum_classes, "\n"))
  end
  if bit_classes ~= nil then
    file:write("\n", table.concat(bit_classes, "\n"))
  end
  if gir_docs.callbacks ~= nil then
    file:write("\n", table.concat(funcs.callback_list(typelib._name, gir_docs.callbacks), "\n"))
  end
  if struct_classes ~= nil then
    file:write("\n", table.concat(struct_classes, "\n"))
  end

  file:write("\n\n", "---@class ", typelib._name)

  if typelib._constant ~= nil then
    file:write("\n", table.concat(constants.list(typelib._constant, gir_docs.constants), "\n"))
  end
  if enum_fields ~= nil then
    file:write("\n", table.concat(enum_fields, "\n"))
  end
  if bit_fields ~= nil then
    file:write("\n", table.concat(bit_fields, "\n"))
  end
  if struct_fields ~= nil then
    file:write("\n", table.concat(struct_fields, "\n"))
  end

  file:write("\n", "local ", typelib._name, " = {}")

  if typelib._function ~= nil and gir_docs.functions ~= nil then
    local fns = funcs.function_list(typelib._name, gir_docs.functions, utils.keys(typelib._function))
    file:write("\n", table.concat(fns, "\n"))
  end

  file:close()
end
