local string, io = string, io
local inspect = require("inspect")

---@param namespace luals_gir.gir.namespace
---@param pkg_name string?
local function write_header(file, namespace, pkg_name)
  local template = [[
---@meta
-- Autogenerated with luals-gir
-- Name: %s
-- Version: %s
]]

  file:write(string.format(template, namespace.name, namespace.version))
  if pkg_name ~= nil then
    file:write("-- Package: ", pkg_name, "\n")
  end
end

---@param output_filename string
---@param gir_data luals_gir.gir
---@return string? err_msg
return function(output_filename, gir_data)
  local file, err = io.open(output_filename, "w")
  if file == nil then
    return err
  end

  local namespace = gir_data.namespace
  write_header(file, namespace, gir_data.pkg ~= nil and gir_data.pkg.name or nil)

  -- TODO: actually generate type annotations
  file:write("return ", inspect(gir_data))

  file:close()
end
