local string, io = string, io
local inspect = require("inspect")

local function write_header(file, namespace, package)
  local template = [[
---@meta
-- Autogenerated with luals-gir
-- Name: %s
-- Version: %s
-- Package: %s
]]

  file:write(string.format(template, namespace._attr.name, namespace._attr.version, package._attr.name))
end

---@param output_filename string
---@param gir_table table
---@return string? err_msg
return function(output_filename, gir_table)
  local file, err = io.open(output_filename, "w")
  if file == nil then
    return err
  end

  local root = gir_table.repository
  local namespace = root.namespace

  write_header(file, namespace, root.package)

  -- TODO: actually generate type annotations
  file:write("return ", inspect(root))

  file:close()
end
